name: fintech
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: SM
      fonts:
        - asset: assets/fonts/SofiaSans-Medium.ttf

    - family: SR
      fonts:
        - asset: assets/fonts/SofiaSans-Regular.ttf

    - family: SSB
      fonts:
        - asset: assets/fonts/SofiaSans-SemiBold.ttf
