name: fintech
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  get_it: ^7.7.0
  flutter_switch: ^0.3.2
  pinput: ^5.0.0
  smooth_page_indicator: ^1.2.0+3
  page_transition: ^2.1.0
  fl_chart: ^0.68.0
  persistent_bottom_nav_bar: ^6.2.1
  flutter_launcher_icons: ^0.13.1

  

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: SM
      fonts:
        - asset: assets/fonts/SofiaSans-Medium.ttf

    - family: SR
      fonts:
        - asset: assets/fonts/SofiaSans-Regular.ttf

    - family: SSB
      fonts:
        - asset: assets/fonts/SofiaSans-SemiBold.ttf


    - family: SB
      fonts:
        - asset: assets/fonts/SofiaSans-Bold.ttf
